sudo: required

services:
  - docker

before_install:
  - docker build -t brkuntmz/sample-docker-react -f Dockerfile.dev .

script:
  - docker run brkuntmz/sample-docker-react npm run test -- --coverage
